server:
  port: 8088

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/any?useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wenhao151

mybatis:
  configuration:
    map-underscore-to-camel-case: true   #开启驼峰命名转换
  mapper-locations: com/spring4all/domain/mapper/*
